jar:
	javac *.java
	jar -cf jpf.jar ActivationFunction.class Add.class CrossEntropy.class CSVWriter.class Dense.class Input.class Layer.class LeakyReLU.class LinearAlgebra.class Linear.class LinearModel.class Loss.class Model.class MSE.class NeuralNetwork.class Optimizer.class PolynomialModel.class RMSProp.class SGD.class Sigmoid.class SimpleModel.class SoftmaxLayer.class Tanh.class Utility.class

clean:
	rm *.class
